#combine all csv files generated by the facebook retrieval code
filenames <- list.files("Washingtonpost", pattern="*.csv", full.names=TRUE)
for (i in 1:length(filenames)){
  if(i == 1){
    dataCom <- read.csv(filenames[i])
  }
  else {
    temp <- read.csv(filenames[i])
    dataCom <- rbind(dataCom, temp)
  }
}
#due to interruptions, some facebook posts are likely to be repeated. They are needed to be removed.
temp1 <- dataCom[!duplicated(dataCom$id), ]

#adding organization column. Please change the name of the organization.
temp1$organization <- "Washingtonpost"

#recover only rows with links. Removes post with only videos and/or photos
temp1 <- temp1[temp1$type == "link",]

#PLease change the file name for other news other news organizations.
file_name <- paste("WashingtonpostLinkOrgUniquePost" , "csv", sep=".")
write.csv(temp1 , file = file_name)
